import { Formatter, Parser } from '../utils/columnRender';
import OptionConstants from '../utils/optionConstants';

module.exports = {
	actions:[
		{
			action:'manager/save',
			icon:'plus-circle-o',
			popupEditor:true,
			title:'新增',
			type:'primary'
		}
	],
	editorSpan:8,
	fields:[
		{
			key:'cccAddress',
			showType:'input',
			title:'地址'
		},
		{
			key:'cccContactName',
			showType:'input',
			title:'联系人名词'
		},
		{
			key:'cccCustomerPmCode',
			showType:'input',
			title:'客户PM代码'
		},
		{
			key:'cccEmail',
			showType:'input',
			title:'邮箱'
		},
		{
			key:'cccIsDefault',
			notAsFilter:true,
			showType:'input',
			title:'是否默认联系人'
		},
		{
			key:'cccMobile',
			notAsFilter:true,
			showType:'input',
			title:'联系手机'
		},
		{
			key:'cccPost',
			notAsFilter:true,
			showType:'input',
			title:'职务'
		},
		{
			key:'cccRemark',
			notAsFilter:true,
			showType:'input',
			title:'备注'
		},
		{
			key:'cccTax',
			notAsFilter:true,
			showType:'input',
			title:'联系传真'
		},
		{
			key:'cccTel',
			notAsFilter:true,
			showType:'input',
			title:'联系电话'
		},
		{
			disabled:true,
			key:'id',
			notAsFilter:true,
			showType:'ID',
			title:'主键'
		},
		{
			key:'pmCode',
			notAsFilter:true,
			showType:'input',
			title:'逻辑主键'
		}
	],
	filterSpan:6
}