import { Formatter, Parser } from '../utils/columnRender';
import OptionConstants from '../utils/optionConstants';

module.exports = {
	actions:[
		{
			action:'manager/save',
			icon:'plus-circle-o',
			popupEditor:true,
			title:'新增',
			type:'primary'
		}
	],
	editorSpan:8,
	fields:[
		{
			key:'ciCustomerPmCode',
			showType:'input',
			title:'公司PM代码'
		},
		{
			key:'ciInsuranceCompany',
			showType:'input',
			title:'保险公司'
		},
		{
			key:'ciInsuranceDeadline',
			showType:'datetime',
			title:'保险截止时间'
		},
		{
			key:'ciInsuranceMaxamount',
			showType:'input',
			title:'单子保险最高金额'
		},
		{
			key:'ciInsuranceNo',
			notAsFilter:true,
			showType:'input',
			title:'保险单号'
		},
		{
			key:'ciRemark',
			notAsFilter:true,
			showType:'input',
			title:'备注'
		},
		{
			disabled:true,
			key:'id',
			notAsFilter:true,
			showType:'ID',
			title:'主键'
		},
		{
			key:'pmCode',
			notAsFilter:true,
			showType:'input',
			title:'逻辑主键'
		}
	],
	filterSpan:6
}